name: GitHub Pacman Game

on:
  # Schedule to run every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allow manual trigger
  workflow_dispatch:

  # Trigger on push to main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Pacman-style contribution animation
      - name: Generate Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Step 3: Deploy generated files to output branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update pacman animation [skip ci]"
